language: node_js
node_js:
- '4.0'
- '6.0'
os:
- linux
- osx
script: curl -s https://raw.githubusercontent.com/Arcanemagus/ci/atomlinter/build-package.sh
  | sh
  && npm run lint
addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
