version: "{build}"
platform: x64
environment:
  APM_TEST_PACKAGES:
  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/Arcanemagus/ci/atomlinter/build-package.ps1'))
test: off
deploy: off
